# Generated by Django 4.2.13 on 2024-05-17 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, verbose_name='Área')),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(blank=True, max_length=45, null=True, verbose_name='Prioridad')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('phone', models.CharField(max_length=9, unique=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Helpdesk.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Abierto', max_length=45, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=200)),
                ('observation', models.TextField(blank=True, max_length=255)),
                ('solution', models.TextField(blank=True, max_length=255)),
                ('opening_date', models.DateField(auto_now_add=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('closure_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_agent', to='Helpdesk.profile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Helpdesk.profile')),
                ('opening_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_agent', to='Helpdesk.profile')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Helpdesk.priority')),
                ('status', models.ForeignKey(default='Nuevo', on_delete=django.db.models.deletion.CASCADE, to='Helpdesk.status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Helpdesk.type')),
            ],
        ),
    ]
