# Generated by Django 4.2.13 on 2024-05-18 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='closure_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closure_agent', to='Helpdesk.profile'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='observation',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='opening_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opening_agent', to='Helpdesk.profile'),
        ),
    ]
